/**
 * Bundle install-time migration entry points into self-contained ESM `.mjs`.
 *
 * Responsibilities:
 * - compile `migrate-package-install.ts` and `migrate-user-config.ts` to plain
 *   JavaScript so the npm `postinstall` and the `npx` bin can run them directly
 * - keep the TypeScript sources as the authored source of truth
 *
 * Why bundling is required:
 * - Node forbids built-in type-stripping for files under `node_modules`
 *   (`ERR_UNSUPPORTED_NODE_MODULES_TYPE_STRIPPING`) and exposes no flag to lift
 *   it. `postinstall` and `install.mjs` execute the migration scripts from inside
 *   the installed package, so `node --experimental-strip-types ./scripts/*.ts`
 *   fails on current Node. Bundling to `.mjs` runs with plain `node` on every
 *   Node version and adds no runtime dependency for consumers (esbuild is
 *   dev-only).
 *
 * Important side effects:
 * - overwrites `scripts/migrate-package-install.mjs` and `scripts/migrate-user-config.mjs`
 *
 * Run: `pnpm run build:install-scripts` (also runs automatically on `npm publish`
 * via `prepublishOnly`). Rebuild whenever the migration TypeScript sources change.
 */

import * as path from "node:path";
import { build } from "esbuild";

/** Banner stamped onto every generated artifact so hand edits are discouraged. */
const BANNER = "/** GENERATED by scripts/build-install-scripts.ts — do not edit by hand. Rebuild with: pnpm run build:install-scripts */";

/** Repository-relative entry points and their bundled `.mjs` outputs. */
const ENTRIES: Array<{ entry: string; out: string }> = [
	{ entry: "scripts/migrate-package-install.ts", out: "scripts/migrate-package-install.mjs" },
	{ entry: "scripts/migrate-user-config.ts", out: "scripts/migrate-user-config.mjs" },
];

/**
 * Bundle a single install-time entry into a self-contained ESM `.mjs`.
 *
 * @param entry Repository-relative `.ts` entry point.
 * @param out Repository-relative `.mjs` output path.
 * @returns esbuild build result.
 */
async function bundleEntry(entry: string, out: string) {
	return build({
		entryPoints: [entry],
		bundle: true,
		format: "esm",
		platform: "node",
		target: "node20",
		outfile: out,
		banner: { js: BANNER },
		sourcemap: false,
		legalComments: "none",
		allowOverwrite: true,
		logLevel: "info",
	});
}

/**
 * Bundle every install-time entry and report the written artifacts.
 *
 * @returns Resolved once all artifacts are written.
 * @throws When esbuild fails to bundle an entry point.
 */
async function main(): Promise<void> {
	await Promise.all(ENTRIES.map((entry) => bundleEntry(entry.entry, entry.out)));
	process.stdout.write(`Bundled install scripts:\n${ENTRIES.map((entry) => `  ${path.normalize(entry.entry)} → ${path.normalize(entry.out)}`).join("\n")}\n`);
}

main().catch((error: unknown) => {
	const message = error instanceof Error ? error.message : String(error);
	process.stderr.write(`Failed to bundle install scripts: ${message}\n`);
	process.exitCode = 1;
});